name: Hello World

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Hello World content
        run: cat hello_world.txt
